---
version: 2.1

# EXECUTORS -----------------------------------------------
executors:
  build:
    parameters:
      mysql_version:
        type: string
        default: 8.0.27
      mysql_command:
        type: string
        default: ""
      ruby_version:
        type: string
      convenience_image_version:
        type: string
    docker:
      - image: <<parameters.convenience_image_version>>/ruby:<<parameters.ruby_version>>
    resource_class: xlarge
    docker:
    environment:
      APP_ENV: test

# COMMANDS ----------------------------------------------
commands:
  setup:
    parameters:
      version:
        type: string
    steps:
      - run:
          name: Install bundler
          command: gem install bundler -v $(tail -n1 Gemfile.lock)
      - run:
          name: Install Ruby gems
          command: bundle install --local --jobs 2 --path vendor/bundle

# JOBS --------------------------------------------------
jobs:
  build:
    parameters:
      ruby_version:
        type: string
        default: 2.5.9
      convenience_image_version:
        type: string
        default: cimg
    executor:
      name: build
      mysql_version: 8.0.27
      mysql_command: --default-authentication-plugin=mysql_native_password
      ruby_version: << parameters.ruby_version >>
      convenience_image_version: << parameters.convenience_image_version >>
    working_directory: /mnt/ramdisk/importer
    steps:
      - setup:
          version: v5

### WORKFLOWS --------------------------------------------
workflows:
  version: 2
  main:
    jobs:
      - build:
          name: new-image
          ruby_version: 2.7.5
          convenience_image_version: cimg
      - build:
          name: deprecated-image
          ruby_version: 2.7.5
          convenience_image_version: circleci
