---
version: 2.1

# EXECUTORS -----------------------------------------------
executors:
  build:
    parameters:
      image:
        type: string
    resource_class: xlarge
    docker:
      - image: <<parameters.image>>

# COMMANDS ----------------------------------------------
commands:
  setup:
    steps:
      - run:
          name: Install bundler
          command: gem install bundler -v $(tail -n1 Gemfile.lock)
      - run:
          name: Install Ruby gems
          command: bundle install --local

# JOBS --------------------------------------------------
jobs:
  build:
    parameters:
      image:
        type: string
        default: cimg/ruby:2.7.5
    executor:
      name: build
      image: << parameters.image >>
    steps:
      - checkout
      - setup

### WORKFLOWS --------------------------------------------
workflows:
  main:
    jobs:
      - build:
          name: new-image
          image: cimg/ruby:2.7.5
      - build:
          name: deprecated-image
          image: circleci/ruby:2.7.5
