---
version: 2.1

# EXECUTORS -----------------------------------------------
executors:
  build:
    parameters:
      ruby_version:
        type: string
      convenience_image_version:
        type: string
    resource_class: xlarge
    docker:
      - image: <<parameters.convenience_image_version>>/ruby:<<parameters.ruby_version>>

# COMMANDS ----------------------------------------------
commands:
  setup:
    steps:
      - run:
          name: Install bundler
          command: gem install bundler -v $(tail -n1 Gemfile.lock)
      - run:
          name: Install Ruby gems
          command: bundle install --local --jobs 2 --path vendor/bundle

# JOBS --------------------------------------------------
jobs:
  build:
    parameters:
      ruby_version:
        type: string
        default: 2.7.5
      convenience_image_version:
        type: string
        default: cimg
    executor:
      name: build
      ruby_version: << parameters.ruby_version >>
      convenience_image_version: << parameters.convenience_image_version >>
    steps:
      - checkout
      - setup

### WORKFLOWS --------------------------------------------
workflows:
  main:
    jobs:
      - build:
          name: new-image
          ruby_version: 2.7.5
          convenience_image_version: cimg
      - build:
          name: deprecated-image
          ruby_version: 2.7.5
          convenience_image_version: circleci
